
# - Only tested with Phred33 quality scores

samples: config/samples.tsv

units: config/units.tsv



#############
### READS ###
#############
reads:
  trim:
    activate: true
    tool: fastp
    params: "--verbose --detect_adapter_for_pe --dont_eval_duplication --trim_poly_g --trim_poly_x --qualified_quality_phred 30 --average_qual 25 --length_required 30 --low_complexity_filter --complexity_threshold 30 --overrepresentation_analysis --correction --overlap_len_require 30 --overlap_diff_limit 5 --overlap_diff_percent_limit 20"

  # Ignored for SE
  collapse:
    activate: true
    params: "--merge"

  extension:
    activate: true
    k: 17
    params: "mode=extend ibb=f prefilter=0 el=100 er=100 overwrite=true trimends=9 ecc=t ecco=f conservative=t ignorebadquality"

  derep:
    activate: true
    # vsearch or seqkit
    tool: vsearch
    params: "--strand both --sizeout --fastaout -"

  low_complex:
    params: "maxns=25 minlen=30 entropy=0.7 entropywindow=30 entropyk=4"



#############
### ALIGN ###
#############
ref:
  hires_organelles_viruses_smags:
      n_shards: 7
      path: "20240313/hires-organelles-viruses-smags.{n_shard}.fas.gz"
        
align:
  map:
    params: "-k 1000 -N 1 -D 15 -R 2 -L 22 -i S,1,1.15 --np 1 --mp '1,1' --rdg '0,1' --rfg '0,1' --score-min 'L,0,-0.1' --no-unal"


  mark_duplicates:
    activate: true
    tool: picard
    params: ""

  calmd:
    activate: false
    params: "-e -E"

bam_filter:
  reassign:
    activate: true
    params: "--iters 0 --min-read-ani 92 --min-read-count 3"

  filter:
    activate: true
    params: "--min-read-ani 92 --min-read-count 3 --min-expected-breadth-ratio 0.75 --min-normalized-entropy 0.6 --min-breadth 0 --min-avg-read-ani 94 --include-low-detection"

  lca:
    activate: true
    params: "--lca-rank genus"



taxonomy:
  nodes: hires-organelles-viruses-smags/20240313/nodes.dmp
  names: hires-organelles-viruses-smags/20240313/names.dmp
  acc2taxid: hires-organelles-viruses-smags.acc2taxid.gz

metadmg:
  damage:
    params: "--min_length 30 --print_length 30"

  lca:
    params: "--weight_type 1 --fix_ncbi 0 --sim_score_low 0.95 --how_many 30"

  dfit:
    params: "--nopt 10 --nbootstrap 20 --showfits 2"

report:
  multiqc: "--verbose --cl-config 'custom_logo: resources/Lundbeck_logo.png' --cl-config 'custom_logo_title: Center for Ancient Environmental Genomics' --cl-config 'custom_logo_url: https://globe.ku.dk/research/caeg/'"
  multiqc_db_url: ""