
# - Only tested with Phred33 quality scores

samples: config/samples.tsv

units: config/units.tsv



#############
### READS ###
#############
reads:
  trim:
    activate: true
    tool: fastp
    params: "--verbose --detect_adapter_for_pe --dont_eval_duplication --trim_poly_g --trim_poly_x --qualified_quality_phred 30 --average_qual 25 --length_required 30 --low_complexity_filter --complexity_threshold 30 --overrepresentation_analysis --correction --overlap_len_require 30 --overlap_diff_limit 5 --overlap_diff_percent_limit 20"

  # Ignored for SE
  collapse:
    activate: true
    params: "--merge"

  extension:
    activate: false
    k: 17
    params: "mode=extend ibb=f prefilter=0 el=100 er=100 overwrite=true trimends=9 ecc=t ecco=f conservative=t ignorebadquality"

  derep:
    activate: true
    # vsearch or seqkit
    tool: seqkit
    params: ""

  low_complex:
    params: "maxns=25 minlen=30 entropy=0.7 entropywindow=30 entropyk=4"



#############
### ALIGN ###
#############
ref:
  refseq_archaea_fungi_virus:
    n_chunks: 1
    path: "refseq_30Aug2022/archaea_fungi_virus/archaea_fungi_virus.fa"
  refseq_invertebrate:
    n_chunks: 3
    path: "refseq_30Aug2022/invertebrate/invert.{n_chunk}"
  refseq_mitochondrion:
    bt2l: False
    n_chunks: 1
    path: "refseq_30Aug2022/mitochondrion/mitochondrion.fa"
  refseq_plant:
    n_chunks: 5
    path: "refseq_30Aug2022/plant/plant.{n_chunk}"
  refseq_plastid:
    bt2l: False
    n_chunks: 1
    path: "refseq_30Aug2022/plastid/plastid.fa"
  refseq_protozoa:
    bt2l: False
    n_chunks: 1
    path: "refseq_30Aug2022/protozoa/protozoa.fa"
  refseq_vertebrate_mammal:
    n_chunks: 10
    path: "refseq_30Aug2022/vertebrate_mammal/vert_mam.{n_chunk}"
  refseq_vertebrate_other:
    n_chunks: 8
    path: "refseq_30Aug2022/vertebrate_other/vert_other.{n_chunk}"
  nt:
    n_chunks: 9
    path: "ncbi_nt_Sept2022/nt.{n_chunk}"
  norway:
    n_chunks: 7
    path: "norway_plant_ctgenoms/norPlantCom.{n_chunk}"
  polar_b3:
    n_chunks: 1
    path: "polar_animals/arctic_animal_b3.fa"
  polar:
    n_chunks: 1
    path: "polar_animals/arctic_animals.fa"
  polar_other:
    n_chunks: 1
    path: "polar_animals/arctic_animals_other.fa"

align:
  map:
    params: "-k 1000 -D 15 -R 2 -L 22 -i S,1,1.15 --np 1 --mp '1,1' --rdg '0,1' --rfg '0,1' --score-min 'L,0,-0.1' --no-unal"

  mark_duplicates:
    activate: false
    tool: markdup
    params: "-d 2500"

  calmd:
    activate: false
    params: "-e -E"

bam_filter:
  reassign:
    activate: true
    params: "--iters 0 --min-read-ani 94 --min-read-count 3"

  filter:
    activate: true
    params: "--min-read-ani 94 --min-read-count 3 --min-expected-breadth-ratio 0.5 --min-normalized-entropy auto --min-normalized-gini auto --min-breadth 0 --min-avg-read-ani 90 --min-coverage-evenness 0.4 --min-coverage-mean 0 --include-low-detection"

  lca:
    activate: true
    params: "--lca-rank genus"

taxonomy:
  nodes: 20230825/ncbi/taxonomy/nodes.dmp
  names: 20230825/ncbi/taxonomy/names.dmp
  acc2taxid: combined_accession2taxid_20221112.gz

metadmg:
  damage:
    params: "--min_length 30 --print_length 30"

  lca:
    params: "--weight_type 1 --fix_ncbi 0 --sim_score_low 0.95 --how_many 30"

  dfit:
    params: "--nopt 10 --nbootstrap 20 --showfits 2"

report:
  multiqc: "--verbose --cl-config 'custom_logo: resources/Lundbeck_logo.png' --cl-config 'custom_logo_title: Center for Ancient Environmental Genomics' --cl-config 'custom_logo_url: https://globe.ku.dk/research/caeg/'"
  multiqc_db_url: ""
